__version__ = "0.1.0"

NOT_LEGAL_ADVICE = (
    "DRAFT - NOT LEGAL ADVICE. Auto-generated by ProSe (Project JusticeStack) to assist "
    "self-representation only. Verify all citations, jurisdictional rules, and deadlines "
    "with a qualified attorney before filing."
)